bot:
  token: '0'
  enabled_chats:
    - -1001805888006


enginetribe_api:
  host: "http://enginetribe.gq:30000"
  api_key: "enginetribe"
  token: "0"



webhook: # To upload level files
  host: "0.0.0.0"
  port: 5585